[tools]
deno = "2.3.5"
go = "1.24.4"
java = "adoptopenjdk-17.0.15+6"
kotlin = "2.1.21"
node = "22.16.0"
"npm:@anthropic-ai/claude-code" = "latest"
ruby = "3.4.4"

[settings]
idiomatic_version_file_enable_tools = ["python"]
