[tools]
bun = "1.2.21"
deno = "2.3.5"
go = "1.24.4"
java = "jetbrains-jre-17.0.14-b1367.22"
kotlin = "2.1.21"
node = "22.16.0"
ruby = "3.4.4"

[settings]
idiomatic_version_file_enable_tools = ["python"]
